DROP TABLE BOARD_LIKE CASCADE CONSTRAINTS;
CREATE TABLE BOARD_LIKE (
    BOARD_NO NUMBER,
    MEMBER_NO NUMBER,
    CONSTRAINT PK_BOARD_LIKE PRIMARY KEY (BOARD_NO, MEMBER_NO)
);
SELECT * FROM BOARD_LIKE;
COMMIT;