CREATE TABLE PRODUCT (
    PRODUCT_ID   VARCHAR2(50) PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(100) NOT NULL,
    PRICE        NUMBER NOT NULL,
    STOCK        NUMBER NOT NULL,
    CREATED_AT   DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT CK_PRODUCT_PRICE CHECK (PRICE >= 0),
    CONSTRAINT CK_PRODUCT_STOCK CHECK (STOCK >= 0)
);

CREATE TABLE ORDERS (
    ORDER_ID    VARCHAR2(50) PRIMARY KEY,
    ORDER_DATE  DATE DEFAULT SYSDATE NOT NULL,
    QUANTITY    NUMBER NOT NULL,
    STATUS      VARCHAR2(20) DEFAULT '주문완료' NOT NULL,
    PRODUCT_ID  VARCHAR2(50) NOT NULL,
    CONSTRAINT FK_ORDERS_PRODUCT 
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCT(PRODUCT_ID),
    CONSTRAINT CK_ORDERS_QUANTITY CHECK (QUANTITY > 0)
);


INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRICE, STOCK)
VALUES ('P001', '마우스', 15000, 50);

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRICE, STOCK)
VALUES ('P002', '키보드', 30000, 20);

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRICE, STOCK) 
VALUES ('P003', '헤드셋', 20000, 30);

INSERT INTO PRODUCT VALUES ('P004', '핸드폰', 200000, 30 , TO_DATE('2026-04-17', 'YYYY-MM-DD'));


INSERT INTO ORDERS (ORDER_ID, QUANTITY, PRODUCT_ID)
VALUES ('O001', 2, 'P001');

INSERT INTO ORDERS (ORDER_ID, QUANTITY, PRODUCT_ID)
VALUES ('O002', 1, 'P002');

INSERT INTO ORDERS (ORDER_ID, QUANTITY, PRODUCT_ID, STATUS)
VALUES ('0003', 3, 'P003', '배송중');

INSERT INTO ORDERS (ORDER_ID, QUANTITY, PRODUCT_ID, STATUS)
VALUES ('0004', 2, 'P004', '상품준비중');

SELECT * FROM PRODUCT;
SELECT * FROM ORDERS;
