CREATE TABLE ORDERS (
    ORDER_NO      NUMBER        PRIMARY KEY,
    MEMBER_NO     NUMBER        NOT NULL REFERENCES MEMBER(MEMBER_NO),
    MENU_NO       NUMBER        NOT NULL REFERENCES MENU(MENU_NO),
    QUANTITY      NUMBER        DEFAULT 1,
    ORDER_DATE    DATE          DEFAULT SYSDATE,
    STATUS        VARCHAR2(20)  DEFAULT '주문접수'
                  CHECK (STATUS IN ('주문접수','조리중','배달중','배달완료','주문취소'))
);
CREATE SEQUENCE SEQ_ORDER_NO START WITH 1 INCREMENT BY 1;



DROP TABLE ORDERS
DROP SEQUENCE 

COMMIT;