CREATE TABLE MEDICAL_RECORS(
	ID NUMBER
);
COMMENT ON TABLE MEDICAL_RECORS IS '진료기록';
COMMENT ON COLUMN MEDICAL_RECORS.ID IS '기록번호';

/*
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
*/
GRANT CREATE VIEW TO C##SC;
-- < 뷰 만들기 >
CREATE VIEW VW_ANIMAL_INFO
AS
SELECT
      K.KEEPER_NAME
     ,A.ANIMAL_NAME
     ,S.SPECIES_NAME
     ,Z.ZONE_NAME
     ,A.WEIGHT_KG
     ,DECODE(A.GENDER, 'M', '수컷', 'F', '암것') "성별"
  FROM
      KEEPER K
  LEFT    
      ANIMAL A USING(KEEPER_ID)
  LEFT
  JOIN
      ZONE Z ON USING(A.ZONE_ID = Z.ZONE_ID)
  LEFT
  JOIN
      SPECIES S USING(SPECIES_ID)

SELECT * FROM VW_ANIMAL_INFO
 WHERE KEEPER_NAME = '제인구달'
 OREDER
    BY ANIMAL_NAME;

-- 데어티 딕셔너리 DICT
SELECT * FROM USER_VIEWS;
SELECT * FROM USER_CONSTRAINTS;
SELECT * FROM USER_TAB_COLUMNS;
SELECT * FROM USER_TABLES;
SELECT * FROM USER_CATALOG;
SELECT * FROM USER_OBJECTS;
SELECT * FROM DICTIONARY;

----------------------------------------------------------
/*
 * 단순 뷰(1개 테이블, 함수/그룹핑 없음) 는 DML 가능
 * 복합 뷰(JOIN, GROUP BY등) DML불가
 * 보통 만들 때 WITH READ ONLY 옵션을 줘서 DML자체를 차단
 */

-- 구역별 통게 SELECT
CREATE OR REPLACE VIEW VW_ZONE_STATS
AS
SELECT
      ZONE_NAME
     ,COUNT(*) "COUNT"
     ,MAX(WEIGHT_KG) "MAX_WEIGHT"
     ,MIN(WEIGHT_KG) "MIN_WEIGHT"
  FROM 
      ANIMAL
  JOIN 
      ZONE USING(ZONE_ID)
 GROUP  
   BY
      ZONE_NAME;
WITH READ ONLY;

SELECT * FROM VW_ZONE_STATS;

 