 /* 회원번호   1,2,3
  * 아이디
  * 비밀번호
  * 이름
  * 이메일
  * 가입일	  SYSDATE
  * 회원정보수정 SYSDATE
  * 삭제여부 	  'Y' / 'N'	 
  */
-- 기존 테이블 삭제
DROP TABLE WEB_MEMBER;

-- 기존 시퀀스 삭제
DROP SEQUENCE SEQ_MEMBER_NO;

-- 테이블 생성
CREATE TABLE WEB_MEMBER(
    USER_NO NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(30) UNIQUE NOT NULL,
    USER_PWD VARCHAR2(30) NOT NULL,
    USER_NAME NVARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(30) NOT NULL,
    ENROLL_DATE DATE DEFAULT SYSDATE,
    MODIFY_DATE DATE DEFAULT SYSDATE,
    STATUS CHAR(1) DEFAULT 'N'
        CHECK(STATUS IN('Y','N'))
);

-- 시퀀스 생성
CREATE SEQUENCE SEQ_MEM_NO
NOCACHE;

SELECT * FROM WEB_MEMBER;
COMMIT;

DROP TABLE  WEB_BOARD;
DROP SEQUENCE SEQ_BOARD;

CREATE SEQUENCE SEQ_WEB
START WITH 1
INCREMENT BY 1;

------------------------------------------------------------

CREATE TABLE WEB_BOARD(
   BOARD_NO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   USER_NO NUMBER REFERENCES WEB_MEMBER,
   BOARD_TITLE NVARCHAR2(50) NOT NULL,
   BOARD_CONTENT NVARCHAR2(2000) NOT NULL,
   CREATE_DATE DATE DEFAULT SYSDATE,
   MODIFY_DATE DATE DEFAULT SYSDATE,
   COUNT NUMBER DEFAULT 0,
   STATUS CHAR(1) DEFAULT 'N' CHECK(STATUS IN ('Y','N'))
);

INSERT INTO
WEB_BOARD(USER_NO, BOARD_TITLE, BOARD_CONTENT)
VALUES(1, '우', '안녕하세요~ 반갑습니다');

INSERT INTO
WEB_BOARD(USER_NO, BOARD_TITLE, BOARD_CONTENT)
VALUES(2, '아', '안녕하세요~ 반갑습니다');

INSERT INTO
WEB_BOARD(USER_NO, BOARD_TITLE, BOARD_CONTENT)
VALUES(1, '오', '안녕하세요~ 반갑습니다');

COMMIT;

SELECT * FROM WEB_BOARD;

SELECT BOARD_NO, BOARD_TITLE, RUM
FROM (
SELECT
      BOARD_NO, BOARD_TITLE, ROWNUM RNUM
 FROM (SELECT 
		  BOARD_NO,
		  BORAR_TITLE,
		  ROWNUM
    FROM
        WEB_BOARD
   ORDER
      BY
        CREATE_DATE DESC))

WHERE
     ROWNUM BETWEEN 4 AND 6;

SELECT
      BOARD_NO
     ,BOARD_TITLE
  FROM
      WEB_BOARD
 ORDER
    BY CREATE_DATE DESC
OFFSET 10 ROWS FETCH NEXT 2 ROWS ONLY;    

SELECT * FROM web_board;

--------------------------------------------------------------

CREATE TABLE WEB_ATTACHMENT(
   FILE_NO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
   REF_BNO NUMBER NOT NULL,
   ORIGIN_NAME VARCHAR2(100) NOT NULL,
   CHANGE_NAME VARCHAR2(50) NOT NULL,
   FILE_PATH VARCHAR2(100) NOT NULL,
   BOARD_TYPE CHAR(1) NOT NULL,
   FILE_LEVEL NUMBER NOT NULL,
   CREATE_DATE DATE DEFAULT SYSDATE
);


