DROP TABLE ORDERS CASCADE CONSTRAINTS;
DROP TABLE PRODUCT CASCADE CONSTRAINTS;

CREATE TABLE PRODUCT (
    PRODUCT_ID   VARCHAR2(50) PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(100) NOT NULL,
    PRICE        NUMBER NOT NULL,
    STOCK        NUMBER NOT NULL,
    CREATED_AT   DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT CK_PRODUCT_PRICE CHECK (PRICE >= 0),
    CONSTRAINT CK_PRODUCT_STOCK CHECK (STOCK >= 0)
);

CREATE TABLE ORDERS (
    ORDER_ID    VARCHAR2(50) PRIMARY KEY,
    ORDER_DATE  DATE DEFAULT SYSDATE NOT NULL,
    QUANTITY    NUMBER NOT NULL,
    STATUS      VARCHAR2(20) DEFAULT '주문완료' NOT NULL,
    PRODUCT_ID  VARCHAR2(50) NOT NULL,
    CONSTRAINT FK_ORDERS_PRODUCT 
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCT(PRODUCT_ID),
    CONSTRAINT CK_ORDERS_QUANTITY CHECK (QUANTITY > 0)
);