-- 회원
CREATE TABLE DELI_MEMBER (
    MEMBER_NO     NUMBER        PRIMARY KEY,
    MEMBER_ID     VARCHAR2(20)  NOT NULL UNIQUE,
    MEMBER_PW     VARCHAR2(20)  NOT NULL,
    MEMBER_NAME   VARCHAR2(30)  NOT NULL,
    ADDRESS       VARCHAR2(100) NOT NULL,
    ENROLL_DATE   DATE DEFAULT SYSDATE
);
CREATE SEQUENCE SEQ_MEMBER_NO START WITH 1 INCREMENT BY 1;

-- 가게
CREATE TABLE RESTAURANT (
    REST_NO       NUMBER        PRIMARY KEY,
    REST_NAME     VARCHAR2(50)  NOT NULL,
    CATEGORY      VARCHAR2(20)  NOT NULL
                  CHECK (CATEGORY IN ('한식','중식','일식','양식','분식','치킨','피자')),
    MIN_PRICE     NUMBER        DEFAULT 0,   -- 최소 주문 금액
    DELIVERY_FEE  NUMBER        DEFAULT 3000,
);
CREATE SEQUENCE SEQ_REST_NO START WITH 1 INCREMENT BY 1;

-- 메뉴 (가게별 메뉴)
CREATE TABLE MENU (
    MENU_NO       NUMBER        PRIMARY KEY,
    REST_NO       NUMBER        NOT NULL REFERENCES RESTAURANT(REST_NO),
    MENU_NAME     VARCHAR2(50)  NOT NULL,
    PRICE         NUMBER        NOT NULL,
    SOLD_OUT      CHAR(1)       DEFAULT 'N' CHECK (SOLD_OUT IN ('Y','N'))  -- Y면 품절
);
CREATE SEQUENCE SEQ_MENU_NO START WITH 1 INCREMENT BY 1;

-- 주문 (1주문 = 1메뉴)
CREATE TABLE ORDERS (
    ORDER_NO      NUMBER        PRIMARY KEY,
    MEMBER_NO     NUMBER        NOT NULL REFERENCES MEMBER(MEMBER_NO),
    MENU_NO       NUMBER        NOT NULL REFERENCES MENU(MENU_NO),
    QUANTITY      NUMBER        DEFAULT 1,
    ORDER_DATE    DATE          DEFAULT SYSDATE,
    STATUS        VARCHAR2(20)  DEFAULT '주문접수'
                  CHECK (STATUS IN ('주문접수','조리중','배달중','배달완료','주문취소'))
);
CREATE SEQUENCE SEQ_ORDER_NO START WITH 1 INCREMENT BY 1;