 -- 자기소개 게시판
 -- 정보공유 게시판
 
 -- 회원 / 게시판
 -- 회원파트 : C(회원가입) / R(로그인)
 -- 게시글 작성 조건 : 로그인  5회 이상
 -- 게시판 : C(게시글작성) / R(목록조회) / R(상세조회)
 CREATE TABLE JDBC_MEMBER(
 	MEMBER_ID VARCHAR2(30) PRIMARY KEY,
 	MEMBER_PWD VARCHAR(30) NOT NULL,
 	MEMBER_NAME VARCHAR(30) NOT NULL 
 );	
 CREATE TABLE JDBC_BOARD(
 	BOARD_NO NUMBER GENERATED ALWAYS AS IDENTITY,
 	BOARD_TITLE NVARCHAR2(2000) NOT NULL,
 	BOARD_CONTENT NVARCHAR2(2000) NOT NULL,
    BOARD_WRITER VARCHAR(30) NOT NULL,
    FOREIGN KEY(BOARD_WRITER) REFERENCES JDBC_MEMBER(MEMBER_ID)
 );
 CREATE TABLE LOGIN_CHECK(
 	LOGIN_ID NUMBER GENERATED ALWAYS AS IDENTITY,
 	MEMBER_ID VARCHAR2(30) NOT NULL,
 	LOGIN_DATE DATE DEFAULT SYSDATE,
 	FOREIGN KEY(MEMBER_ID) REFERENCES JDBC_MEMBER(MEMBER_ID)