CREATE TABLE NOTICE (
	NOTICE_NO NUMBER PRIMARY KEY,          -- 공지번호(PK)
	TITLE  VARCHAR(300) NOT NULL,          -- 제목
	CONTENT CLOB   NOT NULL,       -- 내용
	WRITER VARCHAR2(100) NOT NULL,         -- 작성자
	CREATE_DATE DATE DEFAULT SYSDATE,      -- 작성일
	VIEWS NUMBER DEFAULT 0,                -- 조회수
	IS_TOP CHAR(1) DEFAULT 'N'             -- 상단고정(Y/N)
	);
    ALTER TABLE NOTICE RENAME TO TEST_NOTICE;


-- 공지번호 자동증가 시퀀스
CREATE SEQUENCE SEQ_TEST_NOTICE_NO
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

SELECT * FROM TEST_NOTICE;