CREATE TABLE "MEMBER" (
	"MEMER_ID"	VARCHAR2(20)		NOT NULL,
	"MEMER_EMAIL"	VARCHAR2(50)		NULL,
	"MEMBER_PHONE"	VARCHAR2(15)		NULL,
	"MEMBER_NAME"	VARCHAR2(30)		NOT NULL
);

CREATE TABLE "PRODUCT" (
	"PRODUCT_ID"	VARCHAR2(20)		NOT NULL,
	"PRODUCT_NAME"	VARCHAR2(50)		NOT NULL,
	"PRODUCT_PRICE"	NUMBER(5)		NOT NULL,
	"PRODUCT_STOCK"	NUMBER(5)		NULL
);

CREATE TABLE "ORDERS" (
	"ORDER_ID"	VARCHAR2(20)		NOT NULL,
	"ORDER_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MEMER_ID"	VARCHAR2(20)		NOT NULL,
	"PRODUCT_ID"	VARCHAR2(20)		NOT NULL
);

CREATE TABLE "ORDER DETAIL" (
	"DETAIL_SEQ"	NUMBER(5)		NOT NULL,
	"ORDER_ID"	VARCHAR2(20)		NOT NULL,
	"DETAIL_QTY"	NUMBER(5)		NOT NULL,
	"DETAIL_PRICE"	NUMBER(10)		NOT NULL
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMER_ID"
);

ALTER TABLE "PRODUCT" ADD CONSTRAINT "PK_PRODUCT" PRIMARY KEY (
	"PRODUCT_ID"
);

ALTER TABLE "ORDERS" ADD CONSTRAINT "PK_ORDERS" PRIMARY KEY (
	"ORDER_ID"
);

ALTER TABLE "ORDER DETAIL" ADD CONSTRAINT "PK_ORDER DETAIL" PRIMARY KEY (
	"DETAIL_SEQ",
	"ORDER_ID"
);

ALTER TABLE "ORDER DETAIL" ADD CONSTRAINT "FK_ORDERS_TO_ORDER DETAIL_1" FOREIGN KEY (
	"ORDER_ID"
)
REFERENCES "ORDERS" (
	"ORDER_ID"
);