-- =========================
CREATE TABLE DELI_MEMBER (
    MEMBER_NO     NUMBER        PRIMARY KEY,
    MEMBER_ID     VARCHAR2(20)  NOT NULL UNIQUE,
    MEMBER_PW     VARCHAR2(20)  NOT NULL,
    MEMBER_NAME   VARCHAR2(30)  NOT NULL,
    ADDRESS       VARCHAR2(100) NOT NULL,
    ENROLL_DATE   DATE DEFAULT SYSDATE
);

-- =========================
-- 2. 가게 (부모 테이블)
-- =========================
CREATE TABLE RESTAURANT (
    REST_NO       NUMBER        PRIMARY KEY,
    REST_NAME     VARCHAR2(50)  NOT NULL,
    CATEGORY      VARCHAR2(20)  NOT NULL
                  CHECK (CATEGORY IN ('한식','중식','일식','양식','분식','치킨','피자')),
    MIN_PRICE     NUMBER        DEFAULT 0,
    DELIVERY_FEE  NUMBER        DEFAULT 3000
);

-- =========================
-- 3. 메뉴 (RESTAURANT 참조)
-- =========================
CREATE TABLE MENU (
    MENU_NO       NUMBER        PRIMARY KEY,
    REST_NO       NUMBER        NOT NULL,
    MENU_NAME     VARCHAR2(50)  NOT NULL,
    PRICE         NUMBER        NOT NULL,
    SOLD_OUT      CHAR(1)       DEFAULT 'N'
                  CHECK (SOLD_OUT IN ('Y','N')),
    CONSTRAINT FK_MENU_REST
        FOREIGN KEY (REST_NO)
        REFERENCES RESTAURANT(REST_NO)
);

-- =========================
-- 4. 주문 (DELI_MEMBER, MENU 참조)
-- =========================
CREATE TABLE ORDERS (
    ORDER_NO      NUMBER        PRIMARY KEY,
    MEMBER_NO     NUMBER        NOT NULL,
    MENU_NO       NUMBER        NOT NULL,
    QUANTITY      NUMBER        DEFAULT 1,
    ORDER_DATE    DATE          DEFAULT SYSDATE,
    STATUS        VARCHAR2(20)  DEFAULT '주문접수'
                  CHECK (STATUS IN ('주문접수','조리중','배달중','배달완료','주문취소')),
    CONSTRAINT FK_ORDER_MEMBER
        FOREIGN KEY (MEMBER_NO)
        REFERENCES DELI_MEMBER(MEMBER_NO),
    CONSTRAINT FK_ORDER_MENU
        FOREIGN KEY (MENU_NO)
        REFERENCES MENU(MENU_NO)
);



CREATE SEQUENCE SEQ_MEMBER_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_REST_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MENU_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ORDER_NO START WITH 1 INCREMENT BY 1;


INSERT INTO DELI_MEMBER VALUES (SEQ_MEMBER_NO.NEXTVAL, 'user01', 'pass01', '홍길동', '서울 강남구 역삼동', SYSDATE);
INSERT INTO DELI_MEMBER VALUES (SEQ_MEMBER_NO.NEXTVAL, 'user02', 'pass02', '고길동', '서울 마포구 합정동', SYSDATE);
INSERT INTO DELI_MEMBER VALUES (SEQ_MEMBER_NO.NEXTVAL, 'user03', 'pass03', '박길동', '서울 종로구 혜화동', SYSDATE);

-- 가게 5개
INSERT INTO RESTAURANT VALUES (SEQ_REST_NO.NEXTVAL, 'KH분식', '분식', 10000, 2000);
INSERT INTO RESTAURANT VALUES (SEQ_REST_NO.NEXTVAL, 'KH허니콤보', '치킨', 17000, 3000);
INSERT INTO RESTAURANT VALUES (SEQ_REST_NO.NEXTVAL, 'KH반점', '중식', 12000, 2500);
INSERT INTO RESTAURANT VALUES (SEQ_REST_NO.NEXTVAL, 'KH피자', '피자', 15000, 3000);
INSERT INTO RESTAURANT VALUES (SEQ_REST_NO.NEXTVAL, 'KH스시', '일식', 20000, 4000);

-- 메뉴
INSERT INTO MENU VALUES (SEQ_MENU_NO.NEXTVAL, 1, '떡볶이',       4000, 'N');
INSERT INTO MENU VALUES (SEQ_MENU_NO.NEXTVAL, 1, '순대',         4500, 'N');
INSERT INTO MENU VALUES (SEQ_MENU_NO.NEXTVAL, 1, '튀김모둠',     5000, 'N');
INSERT INTO MENU VALUES (SEQ_MENU_NO.NEXTVAL, 2, '허니콤보',    20000, 'N');
INSERT INTO MENU VALUES (SEQ_MENU_NO.NEXTVAL, 2, '레드콤보',    20000, 'Y');
INSERT INTO MENU VALUES (SEQ_MENU_NO.NEXTVAL, 2, '오리지날',    18000, 'N');
INSERT INTO MENU VALUES (SEQ_MENU_NO.NEXTVAL, 3, '짜장면',       6000, 'N');
INSERT INTO MENU VALUES (SEQ_MENU_NO.NEXTVAL, 3, '짬뽕',         7000, 'N');
INSERT INTO MENU VALUES (SEQ_MENU_NO.NEXTVAL, 3, '탕수육',      18000, 'N');
INSERT INTO MENU VALUES (SEQ_MENU_NO.NEXTVAL, 4, '페퍼로니',15000, 'N');
INSERT INTO MENU VALUES (SEQ_MENU_NO.NEXTVAL, 4, '치이이즈',  16000, 'N');
INSERT INTO MENU VALUES (SEQ_MENU_NO.NEXTVAL, 5, '연어초밥',   22000, 'N');
INSERT INTO MENU VALUES (SEQ_MENU_NO.NEXTVAL, 5, '모둠초밥',   28000, 'N');

INSERT INTO ORDERS VALUES (SEQ_ORDERS_NO.NEXTVAL, )

COMMIT;


DELETE FROM MENU
WHERE MENU_NO BETWEEN 14 AND 26;

DROP TABLE ORDERS;