INSERT INTO DELI_MEMBER VALUES (SEQ_MEMBER_NO.NEXTVAL, 'user01', 'pass01', '홍길동', '서울 강남구 역삼동', SYSDATE);
INSERT INTO DELI_MEMBER VALUES (SEQ_MEMBER_NO.NEXTVAL, 'user02', 'pass02', '고길동', '서울 마포구 합정동', SYSDATE);
INSERT INTO DELI_MEMBER VALUES (SEQ_MEMBER_NO.NEXTVAL, 'user03', 'pass03', '박길동', '서울 종로구 혜화동', SYSDATE);

-- 가게 5개
INSERT INTO RESTAURANT VALUES (SEQ_REST_NO.NEXTVAL, 'KH분식', '분식', 10000, 2000);
INSERT INTO RESTAURANT VALUES (SEQ_REST_NO.NEXTVAL, 'KH허니콤보', '치킨', 17000, 3000);
INSERT INTO RESTAURANT VALUES (SEQ_REST_NO.NEXTVAL, 'KH반점', '중식', 12000, 2500);
INSERT INTO RESTAURANT VALUES (SEQ_REST_NO.NEXTVAL, 'KH피자', '피자', 15000, 3000);
INSERT INTO RESTAURANT VALUES (SEQ_REST_NO.NEXTVAL, 'KH스시', '일식', 20000, 4000);

-- 메뉴
INSERT INTO MENU VALUES (SEQ_MENU_NO.NEXTVAL, 1, '떡볶이',       4000, 'N');
INSERT INTO MENU VALUES (SEQ_MENU_NO.NEXTVAL, 1, '순대',         4500, 'N');
INSERT INTO MENU VALUES (SEQ_MENU_NO.NEXTVAL, 1, '튀김모둠',     5000, 'N');
INSERT INTO MENU VALUES (SEQ_MENU_NO.NEXTVAL, 2, '허니콤보',    20000, 'N');
INSERT INTO MENU VALUES (SEQ_MENU_NO.NEXTVAL, 2, '레드콤보',    20000, 'Y');
INSERT INTO MENU VALUES (SEQ_MENU_NO.NEXTVAL, 2, '오리지날',    18000, 'N');
INSERT INTO MENU VALUES (SEQ_MENU_NO.NEXTVAL, 3, '짜장면',       6000, 'N');
INSERT INTO MENU VALUES (SEQ_MENU_NO.NEXTVAL, 3, '짬뽕',         7000, 'N');
INSERT INTO MENU VALUES (SEQ_MENU_NO.NEXTVAL, 3, '탕수육',      18000, 'N');
INSERT INTO MENU VALUES (SEQ_MENU_NO.NEXTVAL, 4, '페퍼로니',15000, 'N');
INSERT INTO MENU VALUES (SEQ_MENU_NO.NEXTVAL, 4, '치이이즈',  16000, 'N');
INSERT INTO MENU VALUES (SEQ_MENU_NO.NEXTVAL, 5, '연어초밥',   22000, 'N');
INSERT INTO MENU VALUES (SEQ_MENU_NO.NEXTVAL, 5, '모둠초밥',   28000, 'N');

COMMIT;